#!/bin/bash

rm -rf ./.config/*
cp -r ~/.config/waybar ./.config/
cp -r ~/.config/cava ./.config/
cp -r ~/.config/hypr ./.config/
cp -r ~/.config/kitty ./.config/
cp -r ~/.config/nvim ./.config/
cp -r ~/.config/rofi ./.config/
cp -r ~/.config/starship.toml ./.config/
cp -r ~/.config/fastfetch/ ./.config/
cp -r ~/.config/swaync/ ./.config/

